{% set name = "aio-pika" %}
{% set version = "7.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:

  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: dec14ddb7e22d04ddc46f656899f7f3a592431cb618719aa7e03dfe85311be17

build:
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - aiormq >=6.4,<7
    - yarl
    - typing_extensions  # [py<=37]

test:
  imports:
    - aio_pika

about:
  home: https://github.com/mosquito/aio-pika
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: aio-pika is a pure python AMQP client library
  description: |
    aio-pika is a pure python AMQP client library
  doc_url: https://github.com/mosquito/aio-pika
  dev_url: https://github.com/mosquito/aio-pika

extra:
  recipe-maintainers:
    - gregfreeman
