schema_version: 1

context:
  name: aio-pika
  version: "10.0.3"
  python_min: "3.11"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name | replace('-', '_') }}-${{ version }}.tar.gz
  sha256: 41776460d7dd7d90b7dac6e149157a71e905479eca315a062fd1e20f0a937d66

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - uv-build
  run:
    - python >=${{ python_min }}
    - aiormq >=7,<8
    - yarl

tests:
  - python:
      imports:
        - aio_pika
      pip_check: true
      python_version:
        - ${{ python_min }}
        - "*"

about:
  license: Apache-2.0
  license_file: LICENSE
  summary: aio-pika is a pure python AMQP client library
  description: |
    aio-pika is a pure python AMQP client library
  homepage: https://github.com/mosquito/aio-pika
  repository: https://github.com/mosquito/aio-pika
  documentation: https://github.com/mosquito/aio-pika

extra:
  recipe-maintainers:
    - akrherz
    - gregfreeman
